### ISSUE TITLE
ModalEditor.js missing

### ISSUE THREAD

**Issue by abathur** [plamzi/MUDPortal-Web-App#2]
I cloned a fresh copy of this and tried to open index.html, but the resource ModalEditor.js came up missing. I don't know for sure if the resource's absence in the repo is the error, or its inclusion in index.html is.

**Comment by hluaces** [comment]
Hey there,

The same thing happened to me when I did a fresh clone.

It seems that ModalEditor.js was renamed to ModalInput.js at some point and wasn't changed in the index.html file.

Regards,
Héctor

**Comment by plamzi** [comment]
Yep, corrected.
